# ==============================
# Datasource - PostgreSQL
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/karyawan
spring.datasource.username=postgres
spring.datasource.password=12345678

# Pool Hikari (opsional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
