package com.spring.review.common;

public enum ErrorCode {
    SUCCESS,

    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    BAD_REQUEST,
    NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,

    USER_NOT_FOUND,
    INVALID_USERNAME_OR_PASSWORD,
    EMAIL_ALREADY_EXISTS,
    EMPLOYEE_NOT_FOUND,
    DEPARTMENT_NOT_FOUND,
    POSITION_NOT_FOUND,
    ACCESS_DENIED,
    TOKEN_EXPIRED,
    INVALID_TOKEN,
    NOTIFICATION_NOT_FOUND,
}

